# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_statz_wrappers", use_symbols = TRUE, package_name = "statz")

#' @usage NULL
#' @useDynLib statz, .registration = TRUE
NULL

#' Compute the sum of a numeric vector.
#' @param x A numeric vector.
#' @return The sum as a double.
#' @export
z_sum <- function(x) .Call(wrap__z_sum, x)

#' Compute the arithmetic mean of a numeric vector.
#' @param x A numeric vector
#' @return The mean as a double.
#' @export
z_mean <- function(x) .Call(wrap__z_mean, x)

#' Compute the median of a numeric vector.
#' @param x A numeric vector.
#' @return The median as a double
#' @export
z_median <- function(x) .Call(wrap__z_median, x)

#' Compute the sample variance of a numeric vector (Bessel-corrected, n-1).
#' @param x A numeric vector.
#' @return The sample variance as a double.
#' @export
z_variance <- function(x) .Call(wrap__z_variance, x)

#' Compute the sample standard deviation of a numeric vector.
#' @param x A numeric vector.
#' @return The sample standard deviation as a double.
#' @export
z_sd <- function(x) .Call(wrap__z_sd, x)

#' Compute the sample covariance of two numeric vectors.
#' @param x A numeric vector.
#' @param y A numeric vector of the same length.
#' @return The sample covariance as a double.
#' @export
z_covariance <- function(x, y) .Call(wrap__z_covariance, x, y)


# nolint end
