# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib statz, .registration = TRUE
NULL

#' Compute the sum of a numeric vector. Naïve summation with Rust's `.sum()` method
#' @param x A numeric vector.
#' @return The sum as a double.
#' @keywords internal
arch_sum <- function(x) .Call(wrap__arch_sum, x)

#' Compute the arithmetic mean of a numeric vector.
#' @param x A numeric vector
#' @return The mean as a double.
#' @keywords internal
arch_mean <- function(x) .Call(wrap__arch_mean, x)

#' Compute the median of a numeric vector.
#' @param x A numeric vector.
#' @return The median as a double
#' @keywords internal
arch_median <- function(x) .Call(wrap__arch_median, x)

#' Compute the sample variance of a numeric vector (Bessel-corrected, n-1).
#' @param x A numeric vector.
#' @return The sample variance as a double.
#' @keywords internal
arch_var <- function(x) .Call(wrap__arch_var, x)

#' Compute the sample standard deviation of a numeric vector.
#' @param x A numeric vector.
#' @return The sample standard deviation as a double.
#' @keywords internal
arch_sd <- function(x) .Call(wrap__arch_sd, x)

#' Compute the sample covariance of two numeric vectors.
#' @param x A numeric vector.
#' @param y A numeric vector of the same length.
#' @return The sample covariance as a double.
#' @keywords internal
arch_cov <- function(x, y) .Call(wrap__arch_cov, x, y)

#' Compute the Pearson correlation coefficient of two numeric vectors.
#' @param x A numeric vector.
#' @param y A numeric vector.
#' @return The sample correlation as a double
#' @keywords internal
arch_cor <- function(x, y) .Call(wrap__arch_cor, x, y)

#' Compute Pearson correlation coefficient, optimized single-pass
#' @param x A numeric vector.
#' @param y A numeric vector.
#' @return The sample correlation as a double
#' @keywords internal
arch_cor_onepass <- function(x, y) .Call(wrap__arch_cor_onepass, x, y)

#' Compute the standard normal cumulative distribution function (CDF)
#'
#' @description
#' Uses the Abramowitz and Stegun (1972, 10th ed.) equation 7.1.26
#' error function approximation. Deprecated in favour of the
#' libm::erfc() implementation but kept as an initial pedagogical version.
#' Maximum absolute error: |ε| < 1.5 × 10^7
#'
#' @param z A z-score (standardised value)
#' @param lower_tail Logical; if TRUE (default), probabilities are P(X <= x).
#' @param log_p Logical; if TRUE, probabilities p are given as ln(p).
#' @return A numeric vector of cumulative probabilities.
#' @keywords internal
arch_pnorm_as <- function(z, lower_tail, log_p) .Call(wrap__arch_pnorm_as, z, lower_tail, log_p)

#' Compute the Poisson probability mass function
#'
#' @description
#' Compute the Poisson cumulative distribution function P(X ≤ x)
#' using log-space PMF evaluation for each term.
#'
#' @param x A numeric (double) vector of non-negative whole numbers.
#' @param lambda The rate parameter (λ > 0).
#' @param log Logical; if TRUE, probabilities p are given as ln(p).
#' @return A numeric vector of probability masses.
#' @keywords internal
arch_ppois_di <- function(x, lambda, log_p) .Call(wrap__arch_ppois_di, x, lambda, log_p)

#' Compute ln Γ(z) using Godfrey's Lanczos coefficient set (g=7, N=9).
#'
#' @description
#' This is a pedagogical implementation of the traditional Lanczos approximation
#' using Paul Godfrey's well-known f64 coefficient set. Unlike the Boost
#' adaptation in `lgamma()`, this uses the standard formulation:
#'
#'   ln Γ(z) = ½ ln(2π) + (z - ½) ln(z + g - ½) - (z + g - ½) + ln S(z)
#'
#' where S(z) = c₀ + Σ(k=1..8) cₖ/(z-1+k) is the Lanczos sum with
#' alternating-sign coefficients, and the formula is evaluated after
#' shifting z → z-1 to convert from Γ(z+1) to Γ(z).
#'
#' This implementation is less precise than `lgamma()` due to potential
#' cancellation in the alternating-sign sum, but is included as a learning
#' exercise.
#'
#' @references
#' - Godfrey, P. "Lanczos Implementation of the Gamma Function."
#'   <http://my.fit.edu/~gabdo/gamma.txt>
#' - <https://www.mrob.com/pub/ries/lanczos-gamma.html>
#'
#' @param z A numeric (double) vector of positive values.
#' @return A numeric vector containing the natural logarithm of the gamma function.
#' @keywords internal
arch_lgamma_godfrey <- function(z) .Call(wrap__arch_lgamma_godfrey, z)

arch_dsc <- function(treated, donors, n_quantiles, penalty, max_iter, tol) .Call(wrap__arch_dsc, treated, donors, n_quantiles, penalty, max_iter, tol)

#' Compute the sum of a numeric vector using Neumaier summation
#'
#' @description
#' This function computes the sum of a numeric vector using the
#' Neumaier summation algorithm for improved numerical stability. It tracks and
#' compensates for truncated floating point bits, preventing precision loss when
#' adding values with high magnitude variation or across large datasets.
#'
#' @param x A numeric (double) vector.
#' @return The sum as a double.
#' @keywords internal
sum <- function(x) .Call(wrap__sum, x)

#' Compute the arithmetic mean of a numeric vector via Neumaier summation
#'
#' @description
#' This function calculates the arithmetic mean of a numeric vector via the
#' Neumaier summation algorithm used in this package's `sum()` implementation.
#' It is highly resistant to floating-point rounding errors when summing vectors
#' with high magnitude ranges or across large datasets.
#'
#' @param x A numeric (double) vector
#' @return The mean as a double.
#' @keywords internal
mean <- function(x) .Call(wrap__mean, x)

#' Compute the median of a numeric vector.
#'
#' @description
#' This function calculates the median of a numeric vector via the
#' Quickselect/Hoare's selection algorithm. Achieves O(N) time complexity
#' compared to O(N log N) full-sort approach.
#'
#' @param x A numeric (double) vector.
#' @return The median as a double
#' @keywords internal
median <- function(x) .Call(wrap__median, x)

#' Compute the sample variance of a numeric vector
#'
#' @description
#' Calculates the sample variance using Welford's online algorithm,
#' updating a running mean and sum of squared deviations in a
#' single pass. This avoids the catastrophic cancellation that affects
#' the textbook `sum(x^2) - sum(x)^2 / n` formulation, where both terms
#' grow with the square of the mean while their difference does not.
#' Relative precision is preserved even when the coefficient of
#' variation is small.
#'
#' @param x A numeric (double vector of length 2 or greater.
#' @return The sample variance as a double, or `NA` is `x` has fewer
#'   than two elements or contains `NA` or `NaN`.
#' @keywords internal
var <- function(x) .Call(wrap__var, x)

#' Compute the sample standard deviation of a numeric vector.
#'
#' @description
#' Calculates the sample standard deviation by taking the
#' square root of the variance, which uses Welford's algorithm.
#'
#' @param x A numeric (double) vector of length 2 or greater.
#' @return The sample standard deviation as a double, or `NA` if `x`
#'   has fewer than two elements or contains `NA` or `NaN`.
#' @keywords internal
sd <- function(x) .Call(wrap__sd, x)

#' Compute the sample covariance of two numeric vectors.
#'
#' @description
#' Calculates the sample covariance using Welford's online algorithm.
#' Co-deviations are updated in a single pass, preventing catastrophic
#' cancellation issues present in the naïve formulation.
#'
#' @param x A numeric (double) vector.
#' @param y A numeric (double) vector of the same length.
#' @return The sample covariance as a double, or `NA` if the vectors
#'   differ in length, have fewer than two elements, or contain `NA`/`NaN`.
#' @keywords internal
cov <- function(x, y) .Call(wrap__cov, x, y)

#' Compute Pearson correlation coefficient
#'
#' @description
#' Calculates the Pearson correlation coefficient via Welford's online algorithm
#' for the variance and covariance accumulators.
#'
#' @param x A numeric (double) vector.
#' @param y A numeric (double) vector of the same length.
#' @return The sample correlation as a double bounded between -1.0 and 1.0,
#'   or `NA` if the vectors differ in length, have fewer than two elements,
#'   contain `NA`/`NaN`, or have zero variance.
#' @keywords internal
cor <- function(x, y) .Call(wrap__cor, x, y)

#' Compute sample quantiles for a numeric vector
#'
#' @description
#' Calculates sample quantiles for the specified probabilities.
#' This implementation replicates R's default Type 7 continupus sample
#' quantile method (linear interpolation).
#'
#' @param x A numeric (double) vector.
#' @param probs A numeric (double) vector of probabilities with values between 0 and 1.
#' @return A numeric (double) vector of calculated quantiles. Returns `NaN`
#'   for any requested probability if `x` is empty.
#' @keywords internal
quantile <- function(x, probs) .Call(wrap__quantile_r, x, probs)

#' Compute the normal probability density function
#'
#' @description
#' Computes the density f(x | μ, σ) for X ~ N(mean, sd^2).
#'
#' @param x A numeric (double) vector of quantiles.
#' @param mean Mean of the normal distribution.
#' @param sd Standard deviation of the normal distribution.
#' @param log Logical; if TRUE, probabilities p are given as ln(p).
#' @return A numeric vector of probability densities.
#' @export
dnorm <- function(x, mean = 0.0, sd = 1.0, log = FALSE) .Call(wrap__dnorm_r, x, mean, sd, log)

#' Compute the normal cumulative distribution function
#'
#' @description
#' Computes Φ(z) = P(X <= x) for X ~ N(mean, sd^2) utilizing the `libm`
#' complementary error function (erfc) for full 64-bit machine precision.
#'
#' @param x A numeric (double) vector of quantiles.
#' @param mean Mean of the normal distribution.
#' @param sd Standard deviation of the normal distribution.
#' @param lower_tail Logical; if TRUE (default), probabilities are P(X <= x).
#' @param log_p Logical; if TRUE, probabilities p are given as ln(p).
#' @return A numeric vector of cumulative probabilities.
#' @export
pnorm <- function(x, mean = 0.0, sd = 1.0, lower_tail = TRUE, log_p = FALSE) .Call(wrap__pnorm_r, x, mean, sd, lower_tail, log_p)

#' Compute the Poisson probability mass function
#'
#' @description
#' Computes P(X = x) using log-space arithmetic to avoid factorial overflow.
#'
#' @param x A numeric (double) vector of non-negative whole numbers.
#' @param lambda The rate parameter (λ > 0).
#' @param log Logical; if TRUE, probabilities p are given as ln(p).
#' @return A numeric vector of probability masses.
#' @export
dpois <- function(x, lambda, log = FALSE) .Call(wrap__dpois_r, x, lambda, log)

#' Compute the Poisson cumulative distribution function
#'
#' @description
#' Computes P(X <= x) using a recurrence relation for numerical stability.
#'
#' @param x A numeric (double) vector of non-negative whole numbers.
#' @param lambda The rate parameter (λ > 0).
#' @param lower_tail Logical; if TRUE (default), probabilities are P(X <= x).
#' @param log_p Logical; if TRUE, probabilities p are given as ln(p).
#' @return A numeric vector of cumulative probabilities.
#' @export
ppois <- function(x, lambda, lower_tail = TRUE, log_p = FALSE) .Call(wrap__ppois_r, x, lambda, lower_tail, log_p)

#' Compute the natural logarithm of the gamma function: ln Γ(z).
#'
#' @description
#' Uses a simplified adaptation of the Boost.Math C++ library's Lanczos
#' approximation (lanczos13m53 parameter set, N=13, G≈6.0247),
#' optimised for IEEE 754 double-precision (f64) arithmetic. The coefficients
#' are from the `lanczos_sum_expG_scaled` variant, which absorbs both the
#' √(2π) constant and the e^G scaling factor into the rational polynomial,
#' eliminating two sources of rounding error.
#'
#' The Lanczos sum is evaluated as a ratio of two degree-12 polynomials
#' P(z)/Q(z) via Horner's method with fused multiply-add (FMA) instructions,
#' avoiding the catastrophic cancellation that can occur with the traditional
#' alternating-sign summation formulation.
#'
#' Maximum approximation error: ~1.2 × 10^17 (near full f64 precision),
#' except for inputs infinitesimally close to 1 and 2.
#'
#' Simplifications relative to the full Boost implementation:
#' - Omits the special Taylor series handling for z near 1 and 2
#'   (costs ~1-2 ULPs in those neighbourhoods)
#' - A precomputed `LN_FACTORIALS` array storing integer inputs from ln(0!) to ln(15!)
#'
#' @references
#' - Boost.Math library: <https://www.boost.org/doc/libs/latest/libs/math/doc/html/math_toolkit/lanczos.html>
#' - Pugh, G.R. (2004). "An Analysis of the Lanczos Gamma Approximation."
#'   PhD thesis, University of British Columbia.
#' - Lanczos, C. (1964). "A Precision Approximation of the Gamma Function."
#'   SIAM Journal on Numerical Analysis, 1(1), 86-96.
#'
#' @param z A numeric (double) vector of positive values.
#' @return A numeric vector containing the natural logarithm of the gamma function.
#' @export
lgamma <- function(z) .Call(wrap__lgamma_r, z)

#' Internal Gamma PDF Engine
#'
#' @description
#' Evaluates the PDF of the Gamma(shape, rate) distribution at x using
#' log-space arithmetic to avoid overflow:
#'
#'   f(x | α, β) = β^α / Γ(α) · x^(α-1) · e^(-βx)
#'
#' Computed as:
#'   ln f = α·ln(β) - ln Γ(α) + (α-1)·ln(x) - β·x
#'
#' The log-gamma term is evaluated via `lgamma()` (Boost adaptation).
#'
#' @param x A positive numeric value
#' @param shape The shape parameter (α > 0)
#' @param rate The rate parameter (β > 0)
#' @param log Logical; if TRUE, return the log-density
#' @return The gamma PDF value at x, or ln(PDF) if log = TRUE
#' @keywords internal
dgamma_rs <- function(x, shape, rate, log) .Call(wrap__dgamma_r, x, shape, rate, log)

#' Internal Gamma CDF Engine
#'
#' @description
#' Compute the gamma CDF: P(X <= x) for X ~ Gamma(shape, rate).
#'
#' Dispatches to `lower_gamma_series` (Taylor series for P) when the
#' scaled argument z = rate · x is small relative to shape, and to
#' `upper_gamma_cf` (Legendre continued fraction for Q) otherwise.
#' The crossover at z = shape + 1 ensures that the directly computed
#' quantity is always the smaller of P and Q, avoiding precision loss
#' from subtraction near 1.
#'
#' @param x A positive numeric value (quantile)
#' @param shape The shape parameter (α > 0)
#' @param rate The rate parameter (β > 0)
#' @return The cumulative probability P(X ≤ x | α, β)
#' @keywords internal
pgamma_rs <- function(x, shape, rate, lower_tail, log_p) .Call(wrap__pgamma_r, x, shape, rate, lower_tail, log_p)

#' Compute the Tweedie probability density function
#'
#' @description
#' Computes the density for a Tweedie random variable using the
#' Dunn & Smyth (2005) series expansion. Parameterised strictly for
#' the compound Poisson-gamma case (1 < p < 2).
#'
#' @param y A numeric (double) vector of quantiles (y >= 0).
#' @param mu The mean parameter (μ >= 0).
#' @param phi The dispersion parameter (φ > 0).
#' @param power The variance power parameter (1 < p < 2).
#' @param log Logical; if TRUE, probabilities p are given as ln(p).
#' @return A numeric vector of probability densities.
#' @export
dtweedie <- function(y, mu, phi, power, log = FALSE) .Call(wrap__dtweedie_r, y, mu, phi, power, log)

#' Compute the Tweedie cumulative distribution function
#'
#' @description
#' Computes the cumulative probability for a Tweedie random variable using the
#' Dunn & Smyth (2005) series expansion. Parameterised strictly for
#' the compound Poisson-gamma case (1 < p < 2).
#'
#' @param y A numeric (double) vector of quantiles (y >= 0).
#' @param mu The mean parameter (μ >= 0).
#' @param phi The dispersion parameter (φ > 0).
#' @param power The variance power parameter (1 < p < 2).
#' @param lower_tail Logical; if TRUE (default), probabilities are P(Y <= y).
#' @param log_p Logical; if TRUE, probabilities p are given as ln(p).
#' @return A numeric vector of cumulative probabilities.
#' @export
ptweedie <- function(y, mu, phi, power, lower_tail = TRUE, log_p = FALSE) .Call(wrap__ptweedie_r, y, mu, phi, power, lower_tail, log_p)

#' Compute the Inverse Gaussian probability density function
#'
#' @description
#' Evaluated natively in log-space for maximum numerical stability.
#'
#' @param y A numeric (double) vector of quantiles (y > 0).
#' @param mu The mean parameter (μ > 0).
#' @param lambda The shape parameter (λ > 0).
#' @param log Logical; if TRUE, probabilities p are given as ln(p).
#' @return A numeric vector of probability densities.
#' @export
dinvgauss <- function(y, mu = 1, lambda = NULL, log = FALSE) .Call(wrap__dinvgauss_r, y, mu, lambda, log)

#' Compute the Inverse Gaussian cumulative distribution function
#'
#' @description
#' Utilizes the standard normal CDF for full machine precision in extreme tails,
#' featuring a structural overflow brake for extreme parameterisations.
#'
#' @param y A numeric (double) vector of quantiles (y > 0).
#' @param mu The mean parameter (μ > 0).
#' @param lambda The shape parameter (λ > 0).
#' @param lower_tail Logical; if TRUE (default), probabilities are P(Y <= y).
#' @param log_p Logical; if TRUE, probabilities p are given as ln(p).
#' @return A numeric vector of cumulative probabilities.
#' @export
pinvgauss <- function(y, mu = 1, lambda = NULL, lower_tail = TRUE, log_p = FALSE) .Call(wrap__pinvgauss_r, y, mu, lambda, lower_tail, log_p)

#' Internal OLS solver
#'
#' @description
#' Handles R <-> Rust FFI translation and engine dispatching for
#' OLS linear modelling.
#'
#' @param x A numeric design matrix.
#' @param y A numeric response vector
#' @param engine A character string specifying the backend ("cholesky" or "qr").
#' @return A list containing coefficients, standard errors, fitted values,
#'   residuals, residual degrees of freedom, and residual standard deviation.
#'
#' @keywords internal
lm_rs <- function(x, y, engine) .Call(wrap__lm_r, x, y, engine)

#' Eigendecomposition via `faer`
#'
#' @description
#' Replicates `base::eigen()` for symmetric matrices, providing an interface to
#' the Rust-native `faer` library instead of LAPACK.
#'
#' @param x A numeric symmetric matrix
#' @return A list containig the eigenvalues (`values`) and eigenvectors (`vectors`).
#' @export
eigen <- function(x) .Call(wrap__eigen, x)

#' Singular Value Decomposition via faer
#'
#' @description
#' Replicates `base::svd()`, providing an interface to the Rust-native `faer` library
#' instead of LAPACK.
#'
#' @param x A numeric matrix.
#' @return A list containing the singular values (`d`), left singular vectors (`u`),
#'   and right singular vectors (`v`).
#' @export
svd <- function(x) .Call(wrap__svd, x)

# nolint end
